# Generated by Django 6.0.4 on 2026-05-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('traitement', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, null=True)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rendezvous.rendezvous')),
            ],
        ),
    ]
